language: php

php:
  - 7.0

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_wait composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
